//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 03:33:06 PM GMT+08:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://policy.msdemo.ckr.org/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ckr.msdemo.policy.ws;
